### ISSUE TITLE
Error Null Reference

### ISSUE THREAD

**Issue by heberholanda** [searica/TerrainTools#1] opened 2023-12-27 04:51 UTC
TerrainTools.Helpers.RadiusModifier.RefreshGhostScale (Player player) (at <f11fb7a6f2d745c08f45b4efbb80cf2c>:0)
TerrainTools.Helpers.RadiusModifier.UpdatePrefix (Player __instance) (at <f11fb7a6f2d745c08f45b4efbb80cf2c>:0)
(wrapper dynamic-method) Player.DMD<Player::Update>(Player)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
TerrainTools.Helpers.RadiusModifier.RefreshGhostScale (Player player) (at <f11fb7a6f2d745c08f45b4efbb80cf2c>:0)
TerrainTools.Helpers.RadiusModifier.UpdatePrefix (Player __instance) (at <f11fb7a6f2d745c08f45b4efbb80cf2c>:0)
(wrapper dynamic-method) Player.DMD<Player::Update>(Player)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
TerrainTools.Helpers.RadiusModifier.RefreshGhostScale (Player player) (at <f11fb7a6f2d745c08f45b4efbb80cf2c>:0)
TerrainTools.Helpers.RadiusModifier.UpdatePrefix (Player __instance) (at <f11fb7a6f2d745c08f45b4efbb80cf2c>:0)
(wrapper dynamic-method) Player.DMD<Player::Update>(Player)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
TerrainTools.Helpers.RadiusModifier.RefreshGhostScale (Player player) (at <f11fb7a6f2d745c08f45b4efbb80cf2c>:0)
TerrainTools.Helpers.RadiusModifier.UpdatePrefix (Player __instance) (at <f11fb7a6f2d745c08f45b4efbb80cf2c>:0)
(wrapper dynamic-method) Player.DMD<Player::Update>(Player)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
TerrainTools.Helpers.RadiusModifier.RefreshGhostScale (Player player) (at <f11fb7a6f2d745c08f45b4efbb80cf2c>:0)
TerrainTools.Helpers.RadiusModifier.UpdatePrefix (Player __instance) (at <f11fb7a6f2d745c08f45b4efbb80cf2c>:0)
(wrapper dynamic-method) Player.DMD<Player::Update>(Player)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
TerrainTools.Helpers.RadiusModifier.RefreshGhostScale (Player player) (at <f11fb7a6f2d745c08f45b4efbb80cf2c>:0)
TerrainTools.Helpers.RadiusModifier.UpdatePrefix (Player __instance) (at <f11fb7a6f2d745c08f45b4efbb80cf2c>:0)
(wrapper dynamic-method) Player.DMD<Player::Update>(Player)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
TerrainTools.Helpers.RadiusModifier.RefreshGhostScale (Player player) (at <f11fb7a6f2d745c08f45b4efbb80cf2c>:0)
TerrainTools.Helpers.RadiusModifier.UpdatePrefix (Player __instance) (at <f11fb7a6f2d745c08f45b4efbb80cf2c>:0)
(wrapper dynamic-method) Player.DMD<Player::Update>(Player)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
TerrainTools.Helpers.RadiusModifier.RefreshGhostScale (Player player) (at <f11fb7a6f2d745c08f45b4efbb80cf2c>:0)
TerrainTools.Helpers.RadiusModifier.UpdatePrefix (Player __instance) (at <f11fb7a6f2d745c08f45b4efbb80cf2c>:0)
(wrapper dynamic-method) Player.DMD<Player::Update>(Player)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
TerrainTools.Helpers.RadiusModifier.RefreshGhostScale (Player player) (at <f11fb7a6f2d745c08f45b4efbb80cf2c>:0)
TerrainTools.Helpers.RadiusModifier.UpdatePrefix (Player __instance) (at <f11fb7a6f2d745c08f45b4efbb80cf2c>:0)
(wrapper dynamic-method) Player.DMD<Player::Update>(Player)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
TerrainTools.Helpers.RadiusModifier.RefreshGhostScale (Player player) (at <f11fb7a6f2d745c08f45b4efbb80cf2c>:0)
TerrainTools.Helpers.RadiusModifier.UpdatePrefix (Player __instance) (at <f11fb7a6f2d745c08f45b4efbb80cf2c>:0)
(wrapper dynamic-method) Player.DMD<Player::Update>(Player)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
TerrainTools.Helpers.RadiusModifier.RefreshGhostScale (Player player) (at <f11fb7a6f2d745c08f45b4efbb80cf2c>:0)
TerrainTools.Helpers.RadiusModifier.UpdatePrefix (Player __instance) (at <f11fb7a6f2d745c08f45b4efbb80cf2c>:0)
(wrapper dynamic-method) Player.DMD<Player::Update>(Player)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
TerrainTools.Helpers.RadiusModifier.RefreshGhostScale (Player player) (at <f11fb7a6f2d745c08f45b4efbb80cf2c>:0)
TerrainTools.Helpers.RadiusModifier.UpdatePrefix (Player __instance) (at <f11fb7a6f2d745c08f45b4efbb80cf2c>:0)
(wrapper dynamic-method) Player.DMD<Player::Update>(Player)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
TerrainTools.Helpers.RadiusModifier.RefreshGhostScale (Player player) (at <f11fb7a6f2d745c08f45b4efbb80cf2c>:0)
TerrainTools.Helpers.RadiusModifier.UpdatePrefix (Player __instance) (at <f11fb7a6f2d745c08f45b4efbb80cf2c>:0)
(wrapper dynamic-method) Player.DMD<Player::Update>(Player)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
TerrainTools.Helpers.RadiusModifier.RefreshGhostScale (Player player) (at <f11fb7a6f2d745c08f45b4efbb80cf2c>:0)
TerrainTools.Helpers.RadiusModifier.UpdatePrefix (Player __instance) (at <f11fb7a6f2d745c08f45b4efbb80cf2c>:0)
(wrapper dynamic-method) Player.DMD<Player::Update>(Player)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
TerrainTools.Helpers.RadiusModifier.RefreshGhostScale (Player player) (at <f11fb7a6f2d745c08f45b4efbb80cf2c>:0)
TerrainTools.Helpers.RadiusModifier.UpdatePrefix (Player __instance) (at <f11fb7a6f2d745c08f45b4efbb80cf2c>:0)
(wrapper dynamic-method) Player.DMD<Player::Update>(Player)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
TerrainTools.Helpers.RadiusModifier.RefreshGhostScale (Player player) (at <f11fb7a6f2d745c08f45b4efbb80cf2c>:0)
TerrainTools.Helpers.RadiusModifier.UpdatePrefix (Player __instance) (at <f11fb7a6f2d745c08f45b4efbb80cf2c>:0)
(wrapper dynamic-method) Player.DMD<Player::Update>(Player)

**Comment by searica** [comment] 2023-12-27 04:55
Hi, would be able to give a bit more context for this? I won't really be able to address it otherwise. Some helpful info to start would be what other mods you're using and the scenario that this error occurred in, ideally as a set of steps that I could use to reproduce the issue.

**Comment by ginsm** [comment] 2024-01-06 12:07
I'm not sure if we have the same exact mod conflict or not but it's the same error so I'll just piggy-back I suppose:

> [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
TerrainTools.Helpers.RadiusModifier.RefreshGhostScale (Player player) (at <5193f7c45fac427d903aa2d42b65c0b5>:0)
TerrainTools.Helpers.RadiusModifier.UpdatePrefix (Player __instance) (at <5193f7c45fac427d903aa2d42b65c0b5>:0)
(wrapper dynamic-method) Player.DMD<Player::Update>(Player)

Here's my modpack: https://valheim.thunderstore.io/package/Syh/Nazarick_Core/

And here's the reproduction steps for me:
1. Select a build piece with your hammer (seems to be fine if no build piece is selected).
2. Swap to the hoe and modify a tool's radius (larger or smaller than default causes the issue; it's fine if default).
3. Swap back to the hammer while the radius is modified.

After doing those steps, you should be unable to switch to any other item, open the build menu, or place the build piece, Basically completely locks you out from doing anything other than movement and it persists until you completely restart the game from what  I've seen (and just spams that error in console).

I set `​RadiusModifier` to `false` to prevent this bug for now within the modpack. And it doesn't seem to occur when modifying the tool's precision or hardness.

**Comment by searica** [comment] 2024-01-06 16:21
Thanks a bunch for the steps to reproduce. Looks like it wasn't a mod conflict but actually an inconsistent bug with AdvancedTerrainModifiers. I was not able to reproduce the null reference error itself but I was able to consistently produce some strange jittering placement using the steps you provided. 

I've just uploaded an updated version to Thunderstore that should fix the issue (version 1.2.4) please let me know how it works on your end once you get a chance to test it.

**Comment by ginsm** [comment] 2024-01-06 16:49
Seems to have fixed the issue completely for me, thanks! :grin:

**Comment by searica** [comment] 2024-01-06 17:18
Great, glad to hear it! As I think your issue is the same as the original error I'll close this issue now then. Thanks for letting me know it's working as intended.

**Closed as completed by searica** 2024-01-06 17:18 UTC
Labels: bug
